### ISSUE TITLE
assets-manifest.json missing

### ISSUE THREAD

**Issue by jishvi** [Simicart/pwacommerce#1]
The file ``assets-manifest.json`` seems to be missing.

![system_log](https://user-images.githubusercontent.com/10036266/46279062-b56de300-c585-11e8-97f4-66fa834ccc5b.jpg)

**Comment by codynguyen1** [comment]
Hi Jishvi,
You need to build PWA (by clicking 'build PWA' button after filled connector information) before turning on redirection.
The building process would load the PWA js package to your Magento server, in which assets-manifest.json is included.
Thank you!

**Comment by jishvi** [comment]
Hi @codynguyen1,
``Build PWA`` button is only available in the paid version.
So I can not use this module unless I buy the paid version?
